insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (41, 'Pyramid, The', 16);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (86, 'Blood Suckers from Outer Space', 16);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (80, 'Fortress 2', 14);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (19, 'Ama lur (Tierra Madre)', 30);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (10, 'The Raid: Redemption', 87);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (74, 'Last Time I Committed Suicide, The', 33);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (12, 'Milky Way (Tejút)', 80);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (98, 'Red Canyon', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (70, 'Sometimes They Come Back... Again', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (55, 'Coupe de Ville', 56);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (27, 'Floating', 78);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (98, 'Preaching to the Perverted', 95);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (69, 'The Fabulous Baron Munchausen', 61);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (26, 'Sea Fog', 49);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (49, 'Brigham City', 73);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (56, 'Moment After, The', 7);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (73, 'The Nutcracker Prince', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (36, 'Affluenza', 90);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (84, 'Day After Trinity, The', 67);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (96, 'Diabolique (Les diaboliques)', 72);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Mr. Sardonicus', 73);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (37, 'Santo vs. las lobas', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (35, 'Tribute to a Bad Man', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (18, 'Friday the 13th Part IV: The Final Chapter', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (4, 'Carmen', 61);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (33, 'Union: The Business Behind Getting High, The', 66);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (2, 'Recess: School''s Out', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (32, 'The Fool', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (93, 'Leif', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (89, 'Mr. Woodcock', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (43, 'There''s Something Wrong with Aunt Diane', 58);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (87, 'Big Fat Liar', 7);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Funny About Love', 11);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (2, 'Twilight', 13);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (58, 'Closet, The (Placard, Le)', 94);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (60, 'Garfield''s Fun Fest', 66);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (39, 'Jesse Stone: Sea Change', 53);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (9, 'Cadillac Man', 64);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (89, 'Navy Seals', 54);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (87, 'Empire State', 18);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (32, 'Why Do Fools Fall In Love?', 50);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'King of Ping Pong, The (Ping-pongkingen)', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (81, 'The Raid', 31);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (31, 'Kirikou and the Sorceress (Kirikou et la sorcière)', 77);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Butter', 79);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (73, 'Apple Dumpling Gang, The', 11);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (83, 'Hamlet, Prince of Denmark', 86);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (78, 'Uncommon Valor', 49);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (20, 'Lifted', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (44, 'Li''l Quinquin', 42);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (75, '1991: The Year Punk Broke', 49);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (65, 'Dead Fury', 87);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (11, 'Phil Ochs: There But for Fortune', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (65, 'Teenage Mutant Ninja Turtles', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (70, 'Lore', 34);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (11, 'Lili''s Apron', 58);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (24, 'Diary of a Chambermaid (Journal d''une femme de chambre, Le)', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (11, 'Laramie Project, The', 44);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'Helter Skelter', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Premature Burial, The', 65);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (40, 'W.', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (21, 'Presentation, or Charlotte and Her Steak (Présentation ou Charlotte et son steak)', 16);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (19, 'Fatal Attraction', 74);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (20, 'Hard Luck', 62);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (91, 'Iceman, The', 19);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (91, 'In the Land of Women', 20);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (49, 'Patch Adams', 57);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (66, 'Voodoo Dawn', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (65, 'Lion King II: Simba''s Pride, The', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (8, 'Family Tree (L''arbre et la forêt)', 79);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (96, 'Sadie Thompson', 42);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (41, 'Scream 2', 78);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (46, 'Bride of Chucky (Child''s Play 4)', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (8, 'Hui Buh: The Castle Ghost', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (66, 'King Ralph', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (29, 'Human Factor, The', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (62, 'Incident at Oglala', 81);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (29, 'Amazonia', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (48, 'Alvin and the Chipmunks: Chipwrecked', 57);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (42, '33 Postcards', 80);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (89, 'Argo', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (85, 'Square, The', 38);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (58, 'Songcatcher', 56);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Odgrobadogroba', 80);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (31, 'Gunfight at Dodge City, The', 87);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (11, 'Mighty Macs, The', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (51, 'Gangster Squad', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (59, 'Viva', 44);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Four Days of Naples, The (Le quattro giornate di Napoli)', 67);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Storm Catcher', 16);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (98, 'Big Bad Wolves', 23);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (4, 'Blood of a Poet, The (Sang d''un poète, Le)', 7);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (62, 'Lady and the Duke, The (Anglaise et le duc, L'')', 81);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (34, 'One Potato, Two Potato', 77);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (55, 'Running On Karma (Daai Zek Lou)', 23);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (60, 'Conquest 1453 (Fetih 1453)', 76);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (22, '21 Hours at Munich', 91);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (74, 'Sleeping Car, The', 91);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (70, 'Burnt by the Sun (Utomlyonnye solntsem)', 7);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (60, 'Ceremony, The (Gishiki)', 19);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (52, 'Battleground', 58);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (36, 'Bridge on the River Kwai, The', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (46, 'Northerners, The (De noorderlingen)', 54);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Lost Souls', 32);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (64, 'Carnegie Hall', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (12, 'Dark Night of the Scarecrow', 66);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (64, 'Hound of the Baskervilles, The', 6);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (42, 'Cromwell', 11);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (32, 'Gurren Lagann: The Lights in the Sky are Stars (Gekijô ban Tengen toppa guren ragan: Ragan hen)', 2);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Involuntary (De ofrivilliga)', 86);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (63, 'Short Cuts', 43);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (57, 'Virtual Sexuality', 23);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (20, 'Flirt', 93);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (9, 'Sometimes in April', 3);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (69, 'Saw', 97);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (64, 'Biggie and Tupac', 80);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (94, 'Aziz Ansari: Buried Alive', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (30, 'Return to Me', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (23, 'Queen of Versailles, The', 7);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (39, 'Dangerous Liaisons', 27);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (38, 'Pride and the Passion, The', 18);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (51, 'Frances', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (4, 'Grand Budapest Hotel, The', 33);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (93, 'Enter the Phoenix (Da lao ai mei li)', 79);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (16, 'StreetDance 3D', 25);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (96, 'Baboona', 6);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (91, 'Red Psalm (Még kér a nép)', 44);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (52, 'Massacre Canyon', 78);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (45, 'Class Act', 77);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (97, 'Border Radio', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (90, 'Zandalee', 35);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (8, 'Poker Club, The', 22);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (35, 'Al Capone', 64);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (63, 'King''s Speech, The', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (63, 'Pigsty (Porcile)', 6);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (62, 'Backyard, The', 79);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (23, 'Client List, The', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (56, 'General Died at Dawn, The', 50);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (93, 'Phil Spector', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (9, 'Hardcover', 53);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (45, 'Born in East L.A.', 70);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (28, 'Sweet Home', 29);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Familie, En', 17);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (91, 'Man of My Life, The (L''homme de sa vie)', 73);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (46, 'I Was a Male War Bride', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Wild Target', 81);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (53, 'Man Who Could Work Miracles, The', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (58, 'Trouble with Angels, The', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (87, 'Bamba, La', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (25, 'Série noire', 65);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Clockwise', 84);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (26, 'FBI: Frikis buscan incordiar', 66);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (62, 'Kill by Inches', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (66, 'Year One', 35);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (21, 'Expelled from Paradise', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Clink of Ice, The (a.k.a.: Sound of Ice Cubes, The) (Le bruit des glaçons)', 72);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (50, 'Dead Men Don''t Wear Plaid', 18);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'Jim Jefferies: Alcoholocaust', 30);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (93, 'Time Stood Still (Il tempo si è fermato)', 51);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (44, 'Lock, Stock & Two Smoking Barrels', 28);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (36, '20,000 Leagues Under the Sea', 70);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (38, 'Silent Running', 19);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (61, 'Hybrid', 98);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (83, 'Mac & Devin Go to High School', 11);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (98, 'Village, The', 6);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (35, 'Sixth of the World, A (Shestaya chast mira)', 52);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (23, 'Blood Trails ', 60);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (66, 'Baron of Arizona, The', 31);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (72, 'Locke', 87);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (70, 'Concert, Le', 1);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (71, 'Lego: The Adventures of Clutch Powers', 36);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (51, 'Saving Santa', 20);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (63, 'Ten Minutes Older: The Cello', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (34, 'Date with an Angel', 50);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (27, 'Anastasia', 79);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'World of Kanako, The (Kawaki.)', 44);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (79, 'Near Dark', 98);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (18, 'Merry Madagascar', 66);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (67, 'Design for Scandal', 40);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (10, 'Woman Always Pays, The (Afgrunden) (Abyss, The)', 34);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (90, 'Four Seasons (Seasons, The) (Vremena goda)', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (77, 'Calloused Hands', 5);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (24, 'Color of Night', 52);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (36, 'Sabah', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (77, 'Sin City: A Dame to Kill For', 41);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (77, 'Union, The', 70);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (41, 'Clean and Sober', 19);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (23, 'Do We Really Need the Moon?', 67);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (1, 'Snatch', 94);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (26, 'Core, The', 46);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (90, 'Doll''s House, A', 13);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (56, 'Leviathan', 30);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (61, 'Devil''s Playground', 84);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (31, 'Four Horsemen', 63);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (73, 'Kings of Recycling (Kierrätyksen kuninkaat)', 59);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (67, 'He Said, She Said', 83);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'White Men Can''t Jump', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Star Wars: Episode I - The Phantom Menace', 25);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (94, 'Reflecting Skin, The', 98);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (30, 'Rasmus på luffen', 1);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (45, 'Kirikou and the Wild Beast (Kirikou et les bêtes sauvages)', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (79, 'Fantomas vs. Scotland Yard', 55);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (40, 'Virgin Territory', 95);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (81, 'Patrik Age 1.5 (Patrik 1,5)', 45);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (29, 'Rabbit Without Ears (Keinohrhasen)', 20);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (44, 'Galaxina', 76);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (4, 'On Golden Pond', 54);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (72, 'Under Fire', 61);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (92, 'Dorian Gray', 88);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (95, 'Devil''s Tomb, The', 95);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Tales of Terror (Kaidan Shin Mimibukuro)', 78);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Retribution (Sakebi)', 90);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (39, 'Casino Royale', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (20, 'The Boy', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (57, 'Proof', 37);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (88, 'Thick as Thieves', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (83, 'Very Good Girls', 12);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (52, 'DysFunktional Family', 9);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (23, 'Dragon Seed', 52);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (97, 'Hunchback of Notre Dame, The', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (78, 'And God Created Woman', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (35, 'Gerhard Richter Painting', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Bad News Bears', 77);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (26, 'Undercover Blues', 96);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (28, 'Darling Lili', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (98, 'Flawless', 91);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (9, 'Cirque du Soleil: Worlds Away', 52);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (51, 'Melinda and Melinda', 64);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (2, 'Dream Man', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Yamla Pagla Deewana 2', 44);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (29, 'Dawn Patrol, The (Flight Commander)', 43);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (62, 'Brainstorm', 55);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Attack Force', 90);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (28, 'Blue Bird, The', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (30, 'Package, The', 51);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (33, 'Murph: The Protector', 28);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (97, 'Friends & Lovers', 93);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (82, 'Battle in Seattle', 1);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (82, 'Very Potter Sequel, A', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (79, 'Made for Each Other', 27);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (82, 'Ricky Gervais Live 3: Fame', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (84, 'Mystery Street', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (77, 'Take a Giant Step', 100);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (33, 'Scout, The', 54);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (67, 'Brass Target', 87);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (40, 'Among Giants', 13);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (88, 'Marcello Mastroianni: I Remember Yes, I Remember (Marcello Mastroianni: mi ricordo, sì, io mi ricordo)', 49);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Ixcanul Volcano', 95);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Chicken Run', 48);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (4, 'Taxi Blues', 51);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (54, 'Banshee Chapter, The', 69);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (44, 'Cannonball Run, The', 3);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (6, 'I Wake Up Screaming', 12);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (30, 'The Lone Wolf Spy Hunt', 17);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (5, 'Apart from You (After Our Separation) (Kimi to wakarete)', 80);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (95, 'Rugrats Movie, The', 50);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (28, 'Enchanted', 26);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Only Two Can Play', 91);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (53, 'Nightmare on Elm Street, A', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (57, 'Amongst Friends', 64);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (50, 'Supercop 2 (Project S) (Chao ji ji hua)', 73);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (65, 'Madagascar', 25);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (45, 'Escape Plan', 11);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (96, 'Faster', 12);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (63, 'Thousand Words, A', 65);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (36, 'Down to the Bone', 71);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (96, 'A Fight For', 8);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (82, 'Girl of the Golden West', 58);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (94, 'Zombies of the Stratosphere', 45);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (17, 'Commare secca, La (Grim Reaper, The)', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (15, 'Joshua', 58);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (46, 'Apnea (Apnoia)', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (65, 'Alvin and the Chipmunks', 33);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (81, 'Bread and Roses', 85);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (47, 'Being Elmo: A Puppeteer''s Journey', 47);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (57, 'Rammbock', 41);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Seconds', 85);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (48, 'Spy Who Loved Me, The', 15);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (39, '2LDK', 43);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (87, 'Voodoo Dawn', 59);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (76, 'Alive', 55);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (75, 'I Think I Love My Wife', 82);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (27, 'Introducing Dorothy Dandridge', 76);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (80, 'Contractor, The', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (6, 'A Cinderella Story: Once Upon a Song', 32);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (31, 'Speed 2: Cruise Control', 46);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (49, 'Pennies from Heaven', 55);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (43, 'Youngblood', 99);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (57, 'Ten Shrews, The (Kymmenen riivinrautaa)', 16);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (59, 'King David', 24);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (68, 'Inauguration of the Pleasure Dome', 13);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (28, 'KM 31: Kilometro 31', 72);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (33, 'Snowball Express', 27);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (53, 'Dear Heart', 75);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (59, 'Last Dragon, The', 72);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (7, 'Gamera: The Giant Monster (Daikaijû Gamera)', 63);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (3, 'Paris Was a Woman', 45);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (46, '3 Ninjas Kick Back', 4);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (50, 'Nymph', 21);
insert into opcion_respuesta (fk_pregunta, opcion_respuesta, porcentaje_exactitud) values (74, 'Wishing Stairs (Yeogo goedam 3: Yeowoo gyedan)', 42);
