insert into recomendacion (fk_opcion_respuesta, recomendacion) values (54, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (148, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (239, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (267, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (282, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (73, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (16, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (155, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (88, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (275, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (285, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (13, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (259, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (42, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (233, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (280, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (129, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (27, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (30, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (97, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (281, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (47, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (12, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (46, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (2, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (5, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (260, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (89, 'Services');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (42, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (121, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (104, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (92, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (10, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (53, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (63, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (196, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (34, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (35, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (95, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (95, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (18, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (194, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (102, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (110, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (57, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (137, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (141, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (95, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (19, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (131, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (143, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (171, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (270, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (153, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (114, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (171, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (70, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (201, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (85, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (231, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (210, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (44, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (153, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (75, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (102, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (97, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (110, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (151, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (182, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (239, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (38, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (228, 'Engineering');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (109, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (172, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (18, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (275, 'Services');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (169, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (237, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (3, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (155, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (191, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (13, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (275, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (277, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (268, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (2, 'Services');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (27, 'Sales');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (59, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (259, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (248, 'Training');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (153, 'Legal');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (77, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (107, 'Marketing');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (243, 'Support');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (272, 'Business Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (135, 'Product Management');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (109, 'Accounting');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (176, 'Research and Development');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (263, 'Human Resources');
insert into recomendacion (fk_opcion_respuesta, recomendacion) values (51, 'Marketing');